name: clearance
description: An eCommerce App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc:
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  image_downloader: ^0.31.0
  flutter_screenutil: ^5.9.0
  lottie: ^2.6.0
  localization: ^2.1.0
  flutter_localizations:                          
    sdk: flutter                                 
  intl: ^0.18.1                                   
  get_it: ^7.6.4       
  flutter_svg: ^2.0.7  
  firebase_analytics: ^10.4.5
  flutter_local_notifications: ^15.1.1
  firebase_messaging: ^14.6.7
  conditional_builder_null_safety: ^0.0.6
  firebase_core: ^2.15.1   
  fluttertoast: ^8.2.2
  store_redirect: ^2.0.1
  top_modal_sheet: ^2.0.1     
  connectivity_plus: ^4.0.2
  device_info_plus: ^9.0.3                




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/mainIcon.png"



  assets:
    - assets/
    - assets/testJson/
    - assets/images/
    - assets/images/account/
    - assets/images/public/
    - assets/images/errors/
    - assets/images/product_details/
    - assets/images/account/my_orders/
    - assets/icons/
    - assets/images/json/



  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
