/// Flutter icons MainLayoutIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MainLayoutIcons
///      fonts:
///       - asset: fonts/MainLayoutIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MainLayoutIcons {
  MainLayoutIcons._();

  static const _kFontFam = 'MainLayoutIcons';
  static const String? _kFontPkg = null;

  static const IconData cart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData categories = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
