// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXa1F2nb3tf6pkhucVR7xq3AsKuKzH-B0',
    appId: '1:404683863617:web:40803664ec8a1f0de9f8c0',
    messagingSenderId: '404683863617',
    projectId: 'clearance-ac83c',
    authDomain: 'clearance-ac83c.firebaseapp.com',
    storageBucket: 'clearance-ac83c.appspot.com',
    measurementId: 'G-HTJK12DBNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Wv42NcE-I3KRk4PN-r_STgL_bY-yUdI',
    appId: '1:404683863617:android:2614f665e82c0203e9f8c0',
    messagingSenderId: '404683863617',
    projectId: 'clearance-ac83c',
    storageBucket: 'clearance-ac83c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu2OfsTzEJ_sWGb9BX3BLU05QBOEXVhFg',
    appId: '1:404683863617:ios:265438d60d212c32e9f8c0',
    messagingSenderId: '404683863617',
    projectId: 'clearance-ac83c',
    storageBucket: 'clearance-ac83c.appspot.com',
    androidClientId: '404683863617-3u6qcf1ptq2kdojf33mgch5o9hdcstak.apps.googleusercontent.com',
    iosClientId: '404683863617-73grbnqegvmhtsh6gmpaqhd2ab9h3hoc.apps.googleusercontent.com',
    iosBundleId: 'ae.clearance',
  );
}
